# Generated by Django 5.0.2 on 2025-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evmapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="flat_number",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="flat_number",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="", max_length=254, null=True),
        ),
    ]
