# Generated by Django 5.0.2 on 2025-10-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evmapp", "0002_remove_booking_flat_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_2h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
