# Generated by Django 5.0.2 on 2025-10-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "evmapp",
            "0003_booking_last_reminder_sent_booking_reminder_24h_sent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONFERENCE", "Conference"),
                    ("WORKSHOP", "Workshop"),
                    ("SEMINAR", "Seminar"),
                    ("CULTURAL", "Cultural Event"),
                    ("SPORTS", "Sports Event"),
                    ("CONCERT", "Concert"),
                    ("EXHIBITION", "Exhibition"),
                    ("NETWORKING", "Networking Event"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="group_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage for group bookings",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                default="Fun Activities Followed by Dinner, Bring Your Friends and Family along!",
                max_length=250,
                null=True,
            ),
        ),
    ]
