# Generated by Django 5.0.2 on 2025-10-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evmapp", "0004_event_category_event_group_discount_and_more"),
    ]

    operations = []
