# Generated by Django 5.0.2 on 2025-11-07 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evmapp", "0006_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="availability_period",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="previous_experience",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="skills_interests",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="availability",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteer",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Inactive", "Inactive"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="volunteer_role",
            field=models.CharField(
                choices=[
                    ("Event Coordinator", "Event Coordinator"),
                    ("Registration Desk", "Registration Desk"),
                    ("Technical Support", "Technical Support"),
                    ("Guest Relations", "Guest Relations"),
                    ("Marketing", "Marketing & Promotion"),
                    ("Logistics", "Logistics & Setup"),
                    ("Security", "Security"),
                    ("First Aid", "First Aid & Safety"),
                    ("Photography", "Photography & Documentation"),
                    ("General", "General Volunteer"),
                ],
                default="General",
                max_length=100,
            ),
        ),
    ]
